/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    AgentRegistry: {
      address: "0x676ABBdD0D53cFBFC1d222E1208Ea9684593E735",
      abi: [
        {
          inputs: [
            {
              internalType: "uint256",
              name: "initialFee",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "agent",
              type: "address",
            },
          ],
          name: "AddressAlreadyRegistered",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "agent",
              type: "address",
            },
          ],
          name: "AgentNotFound",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "serviceEndpoint",
              type: "string",
            },
          ],
          name: "AgentNotFoundForEndpoint",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "agentId",
              type: "uint256",
            },
          ],
          name: "AgentNotFoundForId",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "did",
              type: "string",
            },
          ],
          name: "DIDAlreadyRegistered",
          type: "error",
        },
        {
          inputs: [],
          name: "EmptyString",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "sent",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "required",
              type: "uint256",
            },
          ],
          name: "InsufficientRegistrationFee",
          type: "error",
        },
        {
          inputs: [],
          name: "NotAgent",
          type: "error",
        },
        {
          inputs: [],
          name: "NotOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "serviceEndpoint",
              type: "string",
            },
          ],
          name: "ServiceEndpointAlreadyRegistered",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "agent",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "agentId",
              type: "uint256",
            },
          ],
          name: "AgentDeactivated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "agent",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "did",
              type: "string",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "agentId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "serviceEndpoint",
              type: "string",
            },
          ],
          name: "AgentRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "newFee",
              type: "uint256",
            },
          ],
          name: "RegistrationFeeUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "agentId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newEndpoint",
              type: "string",
            },
          ],
          name: "ServiceEndpointUpdated",
          type: "event",
        },
        {
          inputs: [],
          name: "deactivateAgent",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "agent",
              type: "address",
            },
          ],
          name: "getAgentByAddress",
          outputs: [
            {
              internalType: "string",
              name: "did",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "serviceEndpoint",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "agentId",
              type: "uint256",
            },
          ],
          name: "getAgentById",
          outputs: [
            {
              internalType: "string",
              name: "did",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "serviceEndpoint",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "serviceEndpoint",
              type: "string",
            },
          ],
          name: "getAgentByServiceEndpoint",
          outputs: [
            {
              internalType: "string",
              name: "did",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "serviceEndpointOut",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "agent",
              type: "address",
            },
          ],
          name: "getAgentDID",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "agent",
              type: "address",
            },
          ],
          name: "getAgentServiceEndpoint",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "agent",
              type: "address",
            },
          ],
          name: "isAgentRegistered",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "did",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "string",
              name: "serviceEndpoint",
              type: "string",
            },
          ],
          name: "registerAgent",
          outputs: [
            {
              internalType: "uint256",
              name: "agentId",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "registrationFee",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "newFee",
              type: "uint256",
            },
          ],
          name: "setRegistrationFee",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "newEndpoint",
              type: "string",
            },
          ],
          name: "updateServiceEndpoint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address payable",
              name: "to",
              type: "address",
            },
          ],
          name: "withdrawFees",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41348069,
    },
    Vault: {
      address: "0xDF555B1adED35fA4cAd6F65182848a0eA8d6766E",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_agent",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_perTaskCap",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_perDayCap",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "NotAgent",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "NotAllowed",
          type: "error",
        },
        {
          inputs: [],
          name: "NotOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "would",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "cap",
              type: "uint256",
            },
          ],
          name: "OverPerDay",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "cap",
              type: "uint256",
            },
          ],
          name: "OverPerTask",
          type: "error",
        },
        {
          inputs: [],
          name: "Reentrant",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int32",
              name: "code",
              type: "int32",
            },
          ],
          name: "TransferFailed",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "agent",
              type: "address",
            },
          ],
          name: "AgentSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "ok",
              type: "bool",
            },
          ],
          name: "AllowSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Deposited",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "daySpent",
              type: "uint256",
            },
          ],
          name: "Paid",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "perTaskCap",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "perDayCap",
              type: "uint256",
            },
          ],
          name: "PolicySet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Withdrawn",
          type: "event",
        },
        {
          inputs: [],
          name: "agent",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "allowed",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "daySpent",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "dayStart",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "deposit",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "pay",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "perDayCap",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "perTaskCap",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "policy",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "setAgent",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "bool",
              name: "ok",
              type: "bool",
            },
          ],
          name: "setAllowed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_perTaskCap",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_perDayCap",
              type: "uint256",
            },
          ],
          name: "setPolicy",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41348066,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
